language: clojure
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
# services:
#   - postgresql
env:
  global:
    - PGPORT=5433
before_script:
  - sudo -u postgres psql -c "CREATE USER test WITH PASSWORD 'test'"
  - sudo -u postgres psql -c 'ALTER ROLE test WITH SUPERUSER'
  - sudo -u postgres psql -c 'CREATE DATABASE test_db;' -U postgres
script: env DATABASE_URL="jdbc:postgresql://localhost:5433/test_db?user=test&password=test" lein test
jdk:
  - oraclejdk8
